default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres_container
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default

production:
  <<: *default
  pool: 10
